In [20]:
import numpy as np
a = np.array([0, 1, 0, 2])
mask1 = a[:,None] > a
mask1 = mask1.astype(int)
mask2 = a[:,None] < a
mask2 = mask2.astype(int) * -1
mask = mask1 + mask2

mask_test = np.array([[ 0, -1,  0, -1],
                        [ 1,  0,  1,  -1],
                        [ 0, -1,  0, -1],
                        [ 1,  1,  1,  0]])
assert (mask == mask_test).all()
print(mask)
from itertools import product
print(list(product([0, 1, 2, 3], [0, 1, 2, 3])))
print(mask.flatten())


[[ 0 -1  0 -1]
 [ 1  0  1 -1]
 [ 0 -1  0 -1]
 [ 1  1  1  0]]
[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0), (1, 1), (1, 2), (1, 3), (2, 0), (2, 1), (2, 2), (2, 3), (3, 0), (3, 1), (3, 2), (3, 3)]
[ 0 -1  0 -1  1  0  1 -1  0 -1  0 -1  1  1  1  0]


In [28]:
features = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8]])

m = features[:, None] - features
m = m.reshape(-1, 4)
print(m)

[[ 0  0  0  0]
 [-4 -4 -4 -4]
 [ 4  4  4  4]
 [ 0  0  0  0]]
